#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
if git rev-parse --verify HEAD >/dev/null 2>&1
then
 against=HEAD
else
 # Initial commit: diff against an empty tree object
 against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

npm run prettier 

# Check linter first 
npm run lint 
lintresult=$?

if [ $lintresult -gt 1 ]; then
    echo "Lint check failed, exiting commit" 
    exit 1
fi 
